// tests/access-gate/command-semantics-pkg.test.ts
// package 命令族（package.ts adapter）：npm/yarn/pnpm/npx

import { defineAdapterTests } from "./helpers";

defineAdapterTests("pkg", [
  { cmd: "npm install express", name: "install is execute", cls: "execute" },
  { cmd: "npm test", name: "test is execute", cls: "execute" },
  { cmd: "npm view express", name: "view is inspect", cls: "inspect" },
  { cmd: "pnpm run build", name: "pnpm run is execute", cls: "execute" },
  { cmd: "yarn add lodash", name: "yarn add is execute", cls: "execute" },
  { cmd: "npx some-package", name: "npx execute package is execute", cls: "execute" },
  { cmd: "npx tsx --version", name: "npx execute with args is execute", cls: "execute" },
  { cmd: "npx --version", name: "npx version flag is inspect", cls: "inspect" },
  { cmd: "npx --help", name: "npx help flag is inspect", cls: "inspect" },
  {
    cmd: ["npm view react", "npm outdated", "npm ls", "npm search lodash"],
    name: "inspect subcommands are inspect",
    cls: "inspect",
  },
  {
    cmd: ["npm remove left-pad", "npm uninstall left-pad", "npm update", "npm exec tsc", "npm build"],
    name: "execute subcommands are execute",
    cls: "execute",
  },
  { cmd: "npm install", name: "npm install is execute with network", cls: "execute", effects: ["network"] },
  { cmd: "npm init -y", name: "npm init is modify", cls: "modify" },
  { cmd: "npm publish", name: "npm publish is execute with network", cls: "execute", effects: ["network"] },
  { cmd: ["yarn add lodash", "yarn install"], name: "yarn add and install are execute with network", cls: "execute", effects: ["network"] },
  { cmd: ["yarn remove lodash", "yarn upgrade lodash"], name: "yarn remove and upgrade are execute", cls: "execute" },
  { cmd: ["npm start", "npm stop", "npm restart"], name: "npm run-script shortcuts are execute", cls: "execute", opaque: false },
  { cmd: ["npm prune", "npm pack", "npm link", "npm unlink"], name: "npm prune/pack/link are execute", cls: "execute", opaque: false },
  { cmd: "pnpm add lodash", name: "pnpm add is execute with network", cls: "execute", effects: ["network"] },
  { cmd: "npm cache clean", name: "npm cache clean is modify without opaque", cls: "modify", opaque: false },
  { cmd: "npm version patch", name: "npm version patch is modify without opaque", cls: "modify", opaque: false },
  { cmd: "npm dedupe", name: "npm dedupe is modify without opaque", cls: "modify", opaque: false },
  { cmd: "npm config get registry", name: "npm config get is inspect", cls: "inspect" },
  { cmd: "npm config set registry https://mirror", name: "npm config set writes ~/.npmrc", cls: "modify", opaque: false, intents: [{ operation: "write", rawPath: "~/.npmrc", confidence: "exact" }] },
  // ── T-037: config 目标层级解析 ──
  { cmd: "npm config set --userconfig=conf.ini registry x", name: "npm config set --userconfig writes exact path", cls: "modify", intents: [{ operation: "write", rawPath: "conf.ini", confidence: "exact" }] },
  { cmd: "npm config set --userconfig= registry x", name: "npm config set --userconfig empty value is opaque", cls: "modify", opaque: true },
  { cmd: "npm config set registry x --globalconfig=etc.ini", name: "npm config set trailing --globalconfig writes exact path", cls: "modify", intents: [{ operation: "write", rawPath: "etc.ini", confidence: "exact" }] },
  { cmd: "npm config set -g registry x", name: "npm config set -g writes ~/.npmrc", cls: "modify", intents: [{ operation: "write", rawPath: "~/.npmrc", confidence: "exact" }] },
  { cmd: "npm config delete registry", name: "npm config delete writes ~/.npmrc", cls: "modify", intents: [{ operation: "write", rawPath: "~/.npmrc", confidence: "exact" }] },
  { cmd: "npm config edit", name: "npm config edit writes ~/.npmrc", cls: "modify", intents: [{ operation: "write", rawPath: "~/.npmrc", confidence: "exact" }] },
  { cmd: "npm config set --bogus registry x", name: "npm config set unknown option is opaque", cls: "modify", opaque: true },
  { cmd: "pnpm config set registry https://mirror", name: "pnpm config set writes ~/.npmrc", cls: "modify", intents: [{ operation: "write", rawPath: "~/.npmrc", confidence: "exact" }] },
  { cmd: "npm audit", name: "npm audit is inspect with network", cls: "inspect", effects: ["network"] },
  { cmd: "npm whoami", name: "npm whoami is inspect with network", cls: "inspect", effects: ["network"] },
  { cmd: "npm ping", name: "npm ping is inspect", cls: "inspect" },
  { cmd: "npm help", name: "npm help is inspect", cls: "inspect" },
  { cmd: "npm root", name: "npm root is inspect", cls: "inspect" },
  { cmd: "npm ci", name: "npm ci is execute with network", cls: "execute", effects: ["network"] },
  { cmd: "npm --prefix /tmp/deps ci", name: "npm --prefix ci is execute with network", cls: "execute", effects: ["network"] },
  { cmd: "pnpm ci", name: "pnpm ci is execute with network", cls: "execute", effects: ["network"] },
  { cmd: ["npx --help", "npx -v"], name: "npx help flags are inspect", cls: "inspect" },
  { cmd: "npm bogus", name: "npm unknown subcommand is opaque", cls: "unknown", opaque: true },
]);
