// tests/access-gate/command-semantics-tx.test.ts
// text-transform 命令族（text-transform.ts adapter）：sed/awk/sort/uniq

import { defineAdapterTests } from "./helpers";

defineAdapterTests("tx", [
  { cmd: "sort -o output.txt input.txt", name: "sort -o writes to output file", cls: "modify", intents: [{ operation: "write", rawPath: "output.txt" }, { operation: "read", rawPath: "input.txt" }] },
  { cmd: "sort input.txt", name: "sort without -o is inspect", cls: "inspect" },
  { cmd: "sed -i 's/foo/bar/' file.txt", name: "sed -i is modify (in-place)", cls: "modify" },
  { cmd: "sed 's/foo/bar/' file.txt", name: "sed without -i is inspect", cls: "inspect" },
  { cmd: "uniq -o output.txt input.txt", name: "uniq -o writes to output file", cls: "modify", intents: [{ operation: "write", rawPath: "output.txt" }, { operation: "read", rawPath: "input.txt" }] },
  { cmd: "sort --unknown-flag input.txt", name: "unknown option sets opaque", opaque: true },
  { cmd: "sed --in-place -e 's/foo/bar/' file.txt", name: "sed --in-place is modify", cls: "modify" },
  { cmd: "sed -e 's/foo/bar/' file.txt", name: "sed -e does not treat the expression as a path", cls: "inspect", intents: [{ operation: "read", rawPath: "file.txt" }] },
  { cmd: "sed --expression='s/x/y/' file.txt", name: "sed --expression= does not treat the expression as a path", cls: "inspect", opaque: false, intents: [{ operation: "read", rawPath: "file.txt" }] },
  { cmd: "sed -f script.sed file.txt", name: "sed -f keeps the script file read intent", cls: "inspect", intents: [{ operation: "read", rawPath: "script.sed" }, { operation: "read", rawPath: "file.txt" }] },
  { cmd: "awk -e '{ print }' file.txt", name: "awk -e does not treat the program as a path", cls: "inspect", intents: [{ operation: "read", rawPath: "file.txt" }] },
  { cmd: "awk -f prog.awk file.txt", name: "awk -f keeps the script file read intent", cls: "inspect", intents: [{ operation: "read", rawPath: "prog.awk" }, { operation: "read", rawPath: "file.txt" }] },
  { cmd: "awk --file=prog.awk file.txt", name: "awk --file= keeps the script file read intent", cls: "inspect", intents: [{ operation: "read", rawPath: "prog.awk" }, { operation: "read", rawPath: "file.txt" }] },
  { cmd: "sed -i.bak 's/foo/bar/' file.txt", name: "sed -i.bak is modify without opaque", cls: "modify", opaque: false, intents: [{ operation: "write", rawPath: "file.txt" }] },
  { cmd: "sed --in-place=.bak 's/foo/bar/' file.txt", name: "sed --in-place=.bak is modify without opaque", cls: "modify", opaque: false, intents: [{ operation: "write", rawPath: "file.txt" }] },
  { cmd: "sort --output out.txt in.txt", name: "sort --output writes to the output file", cls: "modify", intents: [{ operation: "write", rawPath: "out.txt" }, { operation: "read", rawPath: "in.txt" }] },
  { cmd: "sort --output=out.txt in.txt", name: "sort --output= writes to the output file", cls: "modify", intents: [{ operation: "write", rawPath: "out.txt" }, { operation: "read", rawPath: "in.txt" }] },
  { cmd: "uniq --output out.txt in.txt", name: "uniq --output writes to the output file", cls: "modify", intents: [{ operation: "write", rawPath: "out.txt" }, { operation: "read", rawPath: "in.txt" }] },
  { cmd: "sort -- -o out.txt", name: "options after -- are treated as file arguments", cls: "inspect", opaque: false, intents: [{ operation: "read", rawPath: "-o" }, { operation: "read", rawPath: "out.txt" }] },
  { cmd: "awk '{ print }' data.txt", name: "awk without -i is inspect", cls: "inspect" },
  { cmd: "awk -F, '{ print $1 }' data.txt", name: "awk -F field separator is consumed without a path intent", cls: "inspect", opaque: false, intents: [{ operation: "read", rawPath: "data.txt" }] },
  { cmd: "awk -F, '{ print }' data.txt", name: "awk -F attached value form is not opaque", cls: "inspect", opaque: false },
  { cmd: "awk -v x=1 '{ print x }' data.txt", name: "awk -v assignment is consumed without a path intent", cls: "inspect", opaque: false, intents: [{ operation: "read", rawPath: "data.txt" }] },
  { cmd: "sed -n -e 's/x/y/p' file.txt", name: "sed -n -e combo is not opaque", cls: "inspect", opaque: false },
  { cmd: "sed --sandbox -E -e 's/x/y/' file.txt", name: "sed -E and --sandbox are flags, not opaque", cls: "inspect", opaque: false },
  { cmd: "sed -l 80 -e 's/x/y/' file.txt", name: "sed -l line length is an expression value", cls: "inspect", opaque: false, intents: [{ operation: "read", rawPath: "file.txt" }] },
  { cmd: "sed 's/x/y/' /etc/passwd", name: "sed positional file produces read intent", cls: "inspect", intents: [{ operation: "read", rawPath: "/etc/passwd" }] },
  { cmd: "awk '{ print $1 }' ~/.ssh/config", name: "awk positional file produces read intent", cls: "inspect", intents: [{ operation: "read", rawPath: "~/.ssh/config" }] },
  { cmd: "sort -n file1.txt file2.txt", name: "sort positional files produce read intents", cls: "inspect", intents: [{ operation: "read", rawPath: "file1.txt" }, { operation: "read", rawPath: "file2.txt" }] },
  { cmd: "uniq -c /etc/passwd", name: "uniq positional file produces read intent", cls: "inspect", intents: [{ operation: "read", rawPath: "/etc/passwd" }] },
  { cmd: "sed -i 's/x/y/' file.txt", name: "sed -i turns positional files into write intents (in-place)", cls: "modify", intents: [{ operation: "write", rawPath: "file.txt" }] },
  { cmd: "sort -t, -k2 -n -r file.txt", name: "sort common flags are not opaque", cls: "inspect", opaque: false, intents: [{ operation: "read", rawPath: "file.txt" }] },
  { cmd: "sort -oout.txt in.txt", name: "sort short inline output value produces a write intent", cls: "modify", intents: [{ operation: "write", rawPath: "out.txt" }, { operation: "read", rawPath: "in.txt" }] },
  { cmd: "awk -vx=1 '{ print x }' data.txt", name: "awk attached -v value is consumed without a path intent", cls: "inspect", opaque: false, intents: [{ operation: "read", rawPath: "data.txt" }] },
  { cmd: "sed -es/x/y/ file.txt", name: "sed attached -e expression is consumed without a path intent", cls: "inspect", opaque: false, intents: [{ operation: "read", rawPath: "file.txt" }] },
  { cmd: "sed -e", name: "expression option with no value is consumed without opaque", cls: "inspect", opaque: false, intents: [] },
  { cmd: "sed -i 's/x/y/'", name: "sed -i without positional files relies on the compiler conservative write", cls: "modify", intents: [] },
]);
