// search 命令族（search.ts adapter）：find/tree/grep/rg/ls

import { defineAdapterTests } from "./semantics-dsl";

defineAdapterTests("search", [
  { cmd: "find . -type f", name: "find produces search intent", cls: "inspect", intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "find -type f -name '*.ts'", name: "find without path defaults to .", cls: "inspect", intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "find /etc -name shadow", name: "find /etc is protected", cls: "inspect", intents: [{ operation: "search", rawPath: "/etc" }] },
  { cmd: "find . -name '*.tmp' -delete", name: "find -delete upgrades to modify", cls: "modify", intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "find . -name '-delete'", name: "find -name pattern value does not trigger destructive upgrade", cls: "inspect", intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "find . -name '-exec'", name: "find -name pattern value -exec stays inspect", cls: "inspect", intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "grep -e -r file.txt", name: "grep pattern value -r is not recursive", cls: "inspect", intents: [{ operation: "read", rawPath: "file.txt" }] },
  { cmd: "find . -name '*.log' -exec rm {} \\;", name: "find -exec upgrades to modify", cls: "modify", intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "find . -name '*.js' -execdir rm {} +", name: "find -execdir upgrades to modify", cls: "modify", intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "find . -ok rm {} \\;", name: "find -ok upgrades to modify", cls: "modify", intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "find . -exec rm {} ';' extra-root", name: "find quoted ; terminates exec and keeps the following root", cls: "modify", intents: [{ operation: "search", rawPath: "." }, { operation: "search", rawPath: "extra-root" }] },
  { cmd: "find . -maxdepth 2 -name '*.ts'", name: "find -maxdepth skips the value", cls: "inspect", intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "find . -newer ref.txt", name: "find -newer consumes reference file", cls: "inspect", intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "find . -name '*.ts' -fprint out.txt", name: "find -fprint writes output file and upgrades to modify", cls: "modify", intents: [{ operation: "search", rawPath: "." }, { operation: "write", rawPath: "out.txt" }] },
  { cmd: "tree -o out.txt /etc", name: "tree -o writes output file and upgrades to modify", cls: "modify", intents: [{ operation: "search", rawPath: "/etc" }, { operation: "write", rawPath: "out.txt" }] },
  { cmd: "grep -d recurse pattern src/", name: "grep -d consumes directory mode", cls: "inspect", intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "tree -L 2 .", name: "tree -L skips the level value", cls: "inspect", intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "grep -r pattern src/", name: "grep -r searches directory", cls: "inspect", intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "grep -rn pattern src/", name: "grep combined flags preserve recursive search", cls: "inspect", intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "grep pattern file.txt", name: "grep without -r produces a read intent", cls: "inspect", intents: [{ operation: "read", rawPath: "file.txt" }] },
  { cmd: "grep --bogus-flag pattern file.txt", name: "grep unknown option is opaque (tightened)", cls: "inspect", opaque: true },
  { cmd: "find . -okdir rm {} \\;", name: "find -okdir destructive predicate upgrades to modify (tightened)", cls: "modify" },
  { cmd: "find . -print", name: "find -print common flag stays non-opaque", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "grep -f patterns.txt src/", name: "grep -f extracts file opt read intent", cls: "inspect", intents: [{ operation: "read", rawPath: "patterns.txt" }, { operation: "read", rawPath: "src/" }] },
  { cmd: "rg pattern", name: "rg searches default root", cls: "inspect", intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "rg -f patterns.txt", name: "rg -f extracts pattern file", cls: "inspect", intents: [{ operation: "read", rawPath: "patterns.txt" }, { operation: "search", rawPath: "." }] },
  { cmd: "rg --glob '*.ts' --type ts pattern src/ /etc", name: "rg skips values for glob and type options", cls: "inspect", intents: [{ operation: "search", rawPath: "src/" }, { operation: "search", rawPath: "/etc" }] },
  { cmd: "rg -n -C 3 pattern AGENTS.md", name: "rg skips context counts", cls: "inspect", intents: [{ operation: "search", rawPath: "AGENTS.md" }] },
  { cmd: "rg -f patterns.txt src/ /etc", name: "rg -f pattern file makes the first positional argument a root", cls: "inspect", intents: [{ operation: "read", rawPath: "patterns.txt" }, { operation: "search", rawPath: "src/" }, { operation: "search", rawPath: "/etc" }] },
  { cmd: "ls", name: "ls defaults to . list intent", cls: "inspect", intents: [{ operation: "list", rawPath: "." }] },
  { cmd: "ls /etc", name: "ls explicit path produces list intent", cls: "inspect", intents: [{ operation: "list", rawPath: "/etc" }] },
  { cmd: "ls src/ tests/", name: "ls multiple paths produce list intents", cls: "inspect", intents: [{ operation: "list", rawPath: "src/" }, { operation: "list", rawPath: "tests/" }] },
  { cmd: "ls -la /home", name: "ls flags like -la are skipped, path still recognized", cls: "inspect", intents: [{ operation: "list", rawPath: "/home" }] },
  { cmd: "ls -l -- -f", name: "ls -- after options treats everything as path", cls: "inspect", intents: [{ operation: "list", rawPath: "-f" }] },
  { cmd: "ls -w 80 /etc", name: "ls -w consumes width value", cls: "inspect", intents: [{ operation: "list", rawPath: "/etc" }] },
  { cmd: "ls --width=80 /etc", name: "ls --width= consumes attached value", cls: "inspect", intents: [{ operation: "list", rawPath: "/etc" }] },
  // grep 官方 regex 引擎族（GNU grep §grep Programs：-E/-G/-F/-P 均无值 flag）
  { cmd: "grep -E 'x' file.txt", name: "grep -E extended-regexp flag stays non-opaque", cls: "inspect", opaque: false, intents: [{ operation: "read", rawPath: "file.txt" }] },
  { cmd: "grep --extended-regexp -r 'x' src/", name: "grep --extended-regexp long form with recursion stays non-opaque", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "grep -F -G -P 'x' file.txt", name: "grep fixed/basic/perl regexp flags stay non-opaque", cls: "inspect", opaque: false, intents: [{ operation: "read", rawPath: "file.txt" }] },
  // grep NUL 短长形式按官方拆分：-z=--null-data、-Z=--null
  { cmd: "grep -z -l 'x' file.txt", name: "grep -z null-data short flag stays non-opaque", cls: "inspect", opaque: false, intents: [{ operation: "read", rawPath: "file.txt" }] },
  { cmd: "grep -Z -l 'x' file.txt", name: "grep -Z null short flag stays non-opaque", cls: "inspect", opaque: false, intents: [{ operation: "read", rawPath: "file.txt" }] },
  { cmd: "grep --null-data -l 'x' file.txt", name: "grep --null-data long flag stays non-opaque", cls: "inspect", opaque: false, intents: [{ operation: "read", rawPath: "file.txt" }] },
  // grep 其余安全选项（D-055 Out of Scope 闭合）；-T/-U/-D/--exclude-from/--line-buffered 均只读
  { cmd: "grep -T -rn 'x' src/", name: "grep -T initial-tab flag non-opaque", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "grep -U 'x' file.txt", name: "grep -U binary flag non-opaque (read intent)", cls: "inspect", opaque: false, intents: [{ operation: "read", rawPath: "file.txt" }] },
  { cmd: "grep -D skip 'x' file.txt", name: "grep -D devices value consumed (non-opaque)", cls: "inspect", opaque: false, intents: [{ operation: "read", rawPath: "file.txt" }] },
  { cmd: "grep --exclude-from skip.txt -rn 'x' src/", name: "grep --exclude-from extracts file read intent", cls: "inspect", opaque: false, intents: [{ operation: "read", rawPath: "skip.txt" }, { operation: "search", rawPath: "src/" }] },
  { cmd: "grep --line-buffered -rn 'x' src/", name: "grep --line-buffered flag non-opaque", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "grep --binary-files=text -rn 'x' src/", name: "grep --binary-files value consumed (non-opaque)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  // rg 14.x 基线：安全无值 flag（此前未建模 → opaque 误拦）
  { cmd: "rg -P 'x' src/", name: "rg -P pcre2 flag stays non-opaque", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "rg -U -S 'x' src/", name: "rg -U multiline and -S smart-case flags stay non-opaque", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "rg -N -I -0 -p 'x' src/", name: "rg -N no-line-number, -I no-filename, -0 null, -p pretty flags stay non-opaque", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "rg -z 'x' src/", name: "rg -z search-zip flag (14.x) stays non-opaque", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "rg -L 'x' src/", name: "rg -L follows symlinks flag stays non-opaque (not files-without-match)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "rg --files-without-match 'x' src/", name: "rg files-without-match remains a long-only flag", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "rg -s 'x' src/", name: "rg -s case-sensitive flag stays non-opaque", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  // rg -E 是 --encoding 取值（与 grep -E 语义不同）：值必须被消费，不成为搜索根
  { cmd: "rg -E utf16le 'x' src/", name: "rg -E encoding consumes its value (stays non-opaque)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  // rg -d 是 --max-depth 短形式（14.x 基线，与 grep -d=--directories 语义不同）：取值 expression，消费深度值
  { cmd: "rg -d 2 'x' src/", name: "rg -d separated max-depth value consumed (non-opaque)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "rg -d2 'x' src/", name: "rg attached max-depth value consumed (non-opaque)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "rg --max-depth 2 'x' src/", name: "rg --max-depth long form consumes its value (non-opaque)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  // rg 其余长度取值短形式（D-055 Out of Scope 闭合）：-M/-T/-r/-j + --engine + --maxdepth 别名，都只读取值
  { cmd: "rg -M 80 'x' src/", name: "rg -M max-columns value consumed (non-opaque)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "rg -T py 'x' src/", name: "rg -T type-not value consumed (non-opaque; differs from grep -T flag)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "rg -r 'repl' 'x' src/", name: "rg -r replace value consumed (non-opaque; differs from grep -r flag)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "rg -j 4 'x' src/", name: "rg -j threads value consumed (non-opaque)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "rg --engine pcre2 'x' src/", name: "rg --engine value consumed (non-opaque)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  { cmd: "rg --maxdepth 2 'x' src/", name: "rg --maxdepth alias consumed (non-opaque)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  // rg -h / -V 是官方短形式（--help / --version），建模为无值 flag；此前 -h 保持 opaque
  { cmd: "rg -h 'x' src/", name: "rg -h is --help short form, modeled non-opaque (was opaque)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "src/" }] },
  // --version / --help：只读信息探测（长形式 + grep/rg 短形式），无值 flag，闭合 D-055 Out of Scope 的 opaque 误拦
  { cmd: "grep --version", name: "grep --version stays non-opaque (no path intents)", cls: "inspect", opaque: false, intents: [] },
  { cmd: "grep -V", name: "grep -V version short flag stays non-opaque (no path intents)", cls: "inspect", opaque: false, intents: [] },
  { cmd: "grep --help", name: "grep --help stays non-opaque (no path intents)", cls: "inspect", opaque: false, intents: [] },
  { cmd: "rg --version", name: "rg --version stays non-opaque (default root search, rg has no requires-recursive)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "rg -V", name: "rg -V version short flag stays non-opaque (default root search)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "rg --help", name: "rg --help stays non-opaque (default root search)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "ls --version", name: "ls --version stays non-opaque (default list root)", cls: "inspect", opaque: false, intents: [{ operation: "list", rawPath: "." }] },
  { cmd: "ls --help", name: "ls --help stays non-opaque (default list root)", cls: "inspect", opaque: false, intents: [{ operation: "list", rawPath: "." }] },
  { cmd: "find --version", name: "find --version stays non-opaque (default search root)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "." }] },
  { cmd: "tree --version", name: "tree --version stays non-opaque (default search root)", cls: "inspect", opaque: false, intents: [{ operation: "search", rawPath: "." }] },
]);
