export function createHostDriverScript(): string {
  return [
    "$ErrorActionPreference = 'Stop'",
    "$utf8NoBom = [System.Text.UTF8Encoding]::new($false)",
    "[Console]::InputEncoding = $utf8NoBom",
    "[Console]::OutputEncoding = $utf8NoBom",
    "$OutputEncoding = $utf8NoBom",
    "function Write-HostResponse($res) {",
    "  $json = $res | ConvertTo-Json -Compress -Depth 10",
    "  [Console]::Out.WriteLine($json)",
    "  [Console]::Out.Flush()",
    "}",
    "while ($null -ne ($line = [Console]::In.ReadLine())) {",
    "  if ([string]::IsNullOrWhiteSpace($line)) { continue }",
    "  $req = $null",
    "  try {",
    "    $req = $line | ConvertFrom-Json",
    "  } catch {",
    "    Write-HostResponse @{ version = 1; seq = 0; ok = $false; error = 'Malformed request JSON' }",
    "    continue",
    "  }",
    "  try {",
    "    switch ($req.type) {",
    "      'ping' {",
    "        Write-HostResponse @{ version = 1; seq = $req.seq; ok = $true; data = @{ pong = $true } }",
    "      }",
    "      'process-identity' {",
    "        $p = [System.Diagnostics.Process]::GetCurrentProcess()",
    "        $data = @{ pid = $p.Id; creationTimeUtc = $p.StartTime.ToUniversalTime().ToString('o') }",
    "        Write-HostResponse @{ version = 1; seq = $req.seq; ok = $true; data = $data }",
    "      }",
    "      'parse-ast' {",
    "        $tokens = $null; $errors = $null",
    "        $ast = [System.Management.Automation.Language.Parser]::ParseInput($req.script, [ref]$tokens, [ref]$errors)",
    "        $hasErrors = ($null -ne $errors -and $errors.Count -gt 0)",
    "        $data = @{",
    "          hasErrors = $hasErrors",
    "          astType = $ast.GetType().Name",
    "        }",
    "        Write-HostResponse @{ version = 1; seq = $req.seq; ok = $true; data = $data }",
    "      }",
    "      default {",
    "        Write-HostResponse @{ version = 1; seq = $req.seq; ok = $false; error = ('Unsupported request type: ' + $req.type) }",
    "      }",
    "    }",
    "  } catch {",
    "    Write-HostResponse @{ version = 1; seq = $req.seq; ok = $false; error = $_.Exception.Message }",
    "  }",
    "}",
  ].join("\n");
}
